debug: False

local_volume_provisioner_image_repo: quay.io/external_storage/local-volume-provisioner
local_volume_provisioner_image_tag: v2.0.0
storage_addon_dir: '{{ kube_config_dir }}/addons/storage_lvm'

# ################ #
# LVM confguration #
# ################ #

# Set the storage class setup on kubernetes node
metal_k8s_storage_class:
  storage_classes:
    local-lvm:
      is_default: true
  lvm_conf:
    default_fstype: 'ext4'
    default_fs_force: False
    default_fs_opts: '-m 0'
    default_mount_opts: 'defaults'
    vgs:
      kubevg:
        host_path: '/mnt/kubevg'
        storage_class: 'local-lvm'
        volumes:
          lv01:
            size: 52G
          lv02:
            size: 52G
          lv03:
            size: 52G
          lv04:
            size: 11G
          lv05:
            size: 11G

#
# You can also customize a specific volume like this
#
#    vgs:
#      kubevg:
#        volumes:
#          lv01:
#            size: 10G
#            fstype: xfs
#            fs_force: True
#            fs_opts: '-m 0 -cc'
#            mount_opts: 'defaults,noatime'
