---
- name: Install module dependencies
  package:
    name: '{{ item }}'
    state: present
  become: true
  with_items: '{{ repository__role_dependencies }}'

- name: Populate Docker registry
  import_tasks: docker.yml

- name: Populate Helm chart repository
  import_tasks: helm.yml

- name: Populate RPM repository
  import_tasks: yum.yml
