- name: Install task dependencies
  package:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - yum-utils
    - createrepo

- name: Create RPM repository directory
  file:
    path: '{{ repository__data }}/www-data/rpm'
    owner: root
    group: root
    mode: '0755'
    state: directory
  become: true

- name: Mirror repositories
  include_tasks: yum-repository.yml
  vars:
    repository: '{{ item }}'
  with_flattened:
    - '{{ repository__yum_repositories }}'
    - '{{ repository__extra_yum_repositories }}'
