- name: 'Copy ElasticSearch deployment files'
  copy:
    src: '../../../vendor/kubernetes-elasticsearch-cluster/{{ item }}'
    dest: '{{ es_addon_dir }}/'
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755
  with_items:
    - es-discovery-svc.yaml
    - es-svc.yaml
    - es-master.yaml
    - es-client.yaml
    - es-data.yaml
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'Deploy ElasticSearch'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ es_addon_dir }}/{{ item }}'
    namespace: '{{ es_namespace }}'
    state: 'latest'
  with_items:
    - es-discovery-svc.yaml
    - es-svc.yaml
    - es-master.yaml
    - es-client.yaml
    - es-data.yaml
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"
