- name: 'create tempfile for nginx-ingress values'
  tempfile:
    state: file
    suffix: yml
  register: nginx_ingress_value_file

- debug:
    var: nginx_ingress_value_file.path
  when: debug|bool

- name: 'copy nginx-ingress values into temporary file'
  copy:
    src: nginx_ingress_values.yml
    dest: '{{ nginx_ingress_value_file.path }}'

- name: 'install nginx ingress'
  command: >-{{
    helm upgrade nginx-ingress
    --install {{ nginx_ingress_release_name }}
    --repo {{ nginx_ingress_repo }}
    --version {{ nginx_ingress_version }}
    --namespace {{ nginx_ingress_namespace }}
    -f {{ nginx_ingress_value_file.path }}
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'remove unneeded nginx-ingress values file'
  file:
    dest: '{{ nginx_ingress_value_file.path }}'
    state: absent
  when: remove_metal_k8s_temporary_file|bool
