- name: 'assert all vgs have a host_path and volumes defined'
  assert:
    that:
      - item.value.volumes|length > 0
      - item.value.host_path|default("") != ""
  with_dict: '{{ metal_k8s_storage_class.lvm.vgs }}'

- name: 'create dir for lvm storage'
  file:
    dest: '{{ item.value.host_path }}'
    state: directory
  with_dict: '{{ metal_k8s_storage_class.lvm.vgs }}'

- name: display vgs in metal_k8s_storage_class
  debug:
    msg: '{{ metal_k8s_storage_class.lvm.vgs }}'
  when: debug|bool

#
# Set a dictionary that will be used for the LVM configuration
# based on the metal_k8s_storage_class var
#
#   ..code::
#
#     {
#         '/dev/mapper/kubevg-lv01' : {
#             'host_path': '/mnt/kubevg',
#             'vg': 'kubevg',
#             'volume': {
#                 'name': 'lv01',
#                 'fstype': 'ext4',
#                 'size': '10G',
#                 'fs_force': False,
#                 'fs_opts': "",
#                 'mount_opts': "",
#             },
#         }
#     }
#

- name: set fact with metal_k8s_storage_class attributes
  set_fact:
    metal_k8s_lvm_conf: >-
      {
        {%- for vg, prop in metal_k8s_storage_class.lvm.vgs.items() -%}
          {%- set host_path = prop.host_path -%}
          {%- for volume in prop.volumes -%}
            {%- set _ = volume.update(
              {'fstype': volume.fstype
                |default(metal_k8s_storage_class.lvm.default_fstype)}) -%}
            {%- set _ = volume.update(
              {'fs_force': volume.fs_force
                |default(metal_k8s_storage_class.lvm.default_fs_force)}) -%}
            {%- set _ = volume.update(
              {'fs_opts': volume.fs_opts
                |default(metal_k8s_storage_class.lvm.default_fs_opts)}) -%}
            {%- set _ = volume.update(
              {'mount_opts': volume.mount_opts
                |default(metal_k8s_storage_class.lvm.default_mount_opts)}) -%}
            {%- set device = '/dev/mapper/' ~ vg ~ '-'
              ~ volume.name.replace("-", "--") -%}
            '{{ device }}': {{ dict(vg=vg,
                volume=volume, host_path=host_path) }},
          {%- endfor -%}
        {%- endfor -%}
      }

- name: display metal_k8s_lvm_conf dictionary
  debug:
    msg: '{{ metal_k8s_lvm_conf }}'
  when: debug|bool

- name: 'create lvm volumes with required size for each vg'
  lvol:
    lv: '{{ item.value.volume.name }}'
    vg: '{{ item.value.vg }}'
    size: '{{ item.value.volume.size }}'
    state: present
    shrink: False
  with_dict: '{{ metal_k8s_lvm_conf }}'

- name: 'create filesystem on each lvm volumes'
  filesystem:
    fstype: '{{ item.value.volume.fstype }}'
    dev: '{{ item.key }}'
    opts: '{{ item.value.volume.fs_opts }}'
    force: '{{ item.value.volume.fs_force }}'
  with_dict: '{{ metal_k8s_lvm_conf }}'

- name: 'get UUIDs of lvm volumes'
  shell: |
    blkid -s UUID -o value {{ item.key }}
  register: metal_k8s_lvm_uuids
  with_dict: '{{ metal_k8s_lvm_conf }}'

- name: display UUIDs
  debug:
    msg: '{{ metal_k8s_lvm_uuids.results }}'
  when: debug|bool

# Update metal_k8s_conf with UUIDs of the filesystems
#
#   ..code::
#
#     {
#         '/dev/mapper/kubevg-lv01' : {
#             'host_path': '/mnt/kubevg',
#             'vg': 'kubevg',
#             'volume': {
#                 'name': 'lv01',
#                 'fstype': 'ext4',
#                 'size': '10G',
#                 'uuid': 'xxxx-yyyy'
#             },
#         }
#     }

- name: update fact metal_k8s_lvm_conf with UUIDs
  set_fact:
    metal_k8s_lvm_conf: >-
      {
        {%- for device, prop in metal_k8s_lvm_conf.items() -%}
          {%- for result in metal_k8s_lvm_uuids.results -%}
            {%- if result.item.key == device -%}
              {%- set _ =  prop.volume.update({'uuid': result.stdout}) -%}
              '{{ device }}': {{ prop }},
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
      }

- name: display metal_k8s_lvm_conf dictionary with UUIDs
  debug:
    msg: '{{ metal_k8s_lvm_conf }}'
  when: debug|bool

- name: 'mount filesystem for each lvm volumes'
  mount:
    path: '{{ item.value.host_path }}/{{ item.value.volume.uuid }}'
    src: UUID={{ item.value.volume.uuid }}
    opts: '{{ item.value.volume.mount_opts }}'
    fstype: '{{ item.value.volume.fstype }}'
    state: mounted
  with_dict: '{{ metal_k8s_lvm_conf }}'
