- name: delete old metrics-server objects
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    name: '{{ item.name }}'
    namespace: '{{ item.namespace|default(omit) }}'
    resource: '{{ item.resource }}'
    state: absent
  with_items:
    - name: metrics-server:system:auth-delegator
      resource: ClusterRoleBinding
    - name: metrics-server-auth-reader
      resource: RoleBinding
      namespace: kube-system
    - name: v1beta1.metrics.k8s.io
      resource: APIService
    - name: metrics-server
      resource: ServiceAccount
      namespace: kube-system
    - name: metrics-server
      resource: Deployment
      namespace: kube-system
    - name: metrics-server
      resource: Service
      namespace: kube-system
    - name: system:metrics-server
      resource: ClusterRole
    - name: system:metrics-server
      resource: ClusterRoleBinding
  run_once: true
  when: kube_metrics_server_uninstall|bool

- name: create tempfile for metrics-server values
  tempfile:
    state: file
    suffix: .yml
  register: kube_metrics_server_values_file

- debug:
    var: kube_metrics_server_values_file
  when: debug|bool

- name: copy metrics-servevr values into temporary file
  copy:
    src: values.yml
    dest: '{{ kube_metrics_server_values_file.path }}'

- name: install metrics-server chart
  command: >-
    {{ bin_dir }}/helm upgrade
    --install
    --repo {{ metrics_server_repo }}
    --version {{ metrics_server_version }}
    --namespace {{ metrics_server_namespace }}
    -f {{ kube_metrics_server_values_file.path }}
    {{ metrics_server_release_name }}
    {{ metrics_server_chart }}
  run_once: true

- name: remove tempfile for metrics-server values
  file:
    dest: '{{ kube_metrics_server_values_file.path }}'
    state: absent
  when: remove_metal_k8s_temporary_file|bool
