---
- name: delete old metrics-server objects
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    name: '{{ item.name }}'
    namespace: '{{ item.namespace|default(omit) }}'
    resource: '{{ item.resource }}'
    state: absent
  with_items:
    - name: metrics-server:system:auth-delegator
      resource: ClusterRoleBinding
    - name: metrics-server-auth-reader
      resource: RoleBinding
      namespace: kube-system
    - name: v1beta1.metrics.k8s.io
      resource: APIService
    - name: metrics-server
      resource: ServiceAccount
      namespace: kube-system
    - name: metrics-server
      resource: Deployment
      namespace: kube-system
    - name: metrics-server
      resource: Service
      namespace: kube-system
    - name: system:metrics-server
      resource: ClusterRole
    - name: system:metrics-server
      resource: ClusterRoleBinding
  run_once: true
  when: kube_metrics_server_uninstall|bool

- name: install metrics-server chart
  helm_cli:
    release: '{{ metrics_server_release_name }}'
    chart:
      name: '{{ metrics_server_chart }}'
      version: '{{ metrics_server_version }}'
      repo: '{{ metrics_server_repo }}'
    namespace: '{{ metrics_server_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: >-
      {{ [kube_metrics_server__default_values] + metrics_server_external_values }}
  register: metrics_server_helm_install
  run_once: true

- debug:
    var: metrics_server_helm_install
  run_once: true
  when: debug|bool
