- name: Check whether Docker config.json exists
  stat:
    path: /root/.docker/config.json
  register: stat_config_json
  become: true

- name: Retrieve Docker repository credentials
  block:
    - name: Read Docker config.json
      command: cat /root/.docker/config.json
      become: true
      register: config_json
      changed_when: false
      check_mode: no

    - name: Set known Docker repository credentials facts
      set_fact:
        repository__docker_creds_user: '{{ ((config_json.stdout | from_json).auths[repository__address].auth | b64decode).split(":", 1)[0] }}'
        repository__docker_creds_password: '{{ ((config_json.stdout | from_json).auths[repository__address].auth | b64decode).split(":", 1)[1] }}'
        repository__docker_login: false
      when:
        - (config_json.stdout | from_json).auths is defined
        - (config_json.stdout | from_json).auths[repository__address] is defined
        - (config_json.stdout | from_json).auths[repository__address].auth is defined
  when:
    - stat_config_json.stat.exists
