- name: 'Copy ElasticSearch deployment files'
  copy:
    src: '../../../vendor/kubernetes-elasticsearch-cluster/{{ item }}'
    dest: '{{ es_addon_dir }}/'
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755
  with_items:
    - es-discovery-svc.yaml
    - es-svc.yaml
    - es-master.yaml
    - es-master-pdb.yaml
    - es-ingest.yaml
    - es-ingest-svc.yaml
    - stateful/es-data-svc.yaml
    - stateful/es-data-stateful.yaml
    - es-data-pdb.yaml
    - es-curator-config.yaml
    - es-curator_v1beta1.yaml
  register: es_manifests
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'Delete old es-client deployment'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    name: 'es-client'
    namespace: '{{ es_namespace }}'
    resource: 'deploy'
    state: 'absent'
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'Delete old elasticsearch service'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    name: 'elasticsearch'
    namespace: '{{ es_namespace }}'
    resource: 'svc'
    state: 'absent'
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'Deploy ElasticSearch'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ es_addon_dir }}/{{ item | basename }}'
    namespace: '{{ es_namespace }}'
    state: 'latest'
  with_items: >-
    {{ es_manifests.results|default([])|map(attribute="item")|list }}
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"
