---

- name: 'install Elasticsearch'
  vars:
    values_file: '{{ role_path }}/files/elasticsearch/values.yml'
  helm_cli:
    release: '{{ elasticsearch_release_name }}'
    chart:
      name: '{{ elasticsearch_chart }}'
      version: '{{ elasticsearch_version }}'
      repo: '{{ elasticsearch_repo }}'
    namespace: '{{ elasticsearch_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: >-
      {{ [
        lookup('file', values_file) | from_yaml
      ] + elasticsearch_external_values }}
    wait: '{{ helm_wait | bool }}'
    state: '{{ helm_state }}'
  register: elasticsearch_helm_install
  run_once: true

- debug:
    var: elasticsearch_helm_install
  run_once: true
  when: debug | bool
