---

- name: 'install Elasticsearch Curator Chart'
  vars:
    values_file: '{{ role_path }}/files/elasticsearch-curator/values.yml'
  helm_cli:
    release: '{{ elasticsearch_curator_release_name }}'
    chart:
      name: '{{ elasticsearch_curator_chart }}'
      version: '{{ elasticsearch_curator_version }}'
      repo: '{{ elasticsearch_curator_repo }}'
    namespace: '{{ elasticsearch_curator_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: >-
      {{ [
        lookup('file', values_file) | from_yaml
      ] + elasticsearch_curator_external_values }}
    wait: '{{ helm_wait | bool }}'
    state: '{{ helm_state }}'
  register: elasticsearch_curator_helm_install
  run_once: true

- debug:
    var: elasticsearch_curator_helm_install
  run_once: true
  when: debug | bool
