---
- name: install Heapster chart
  helm_cli:
    release: '{{ heapster_release_name }}'
    chart:
      name: heapster
      version: '{{ heapster_version }}'
      repo: '{{ heapster_repo }}'
    namespace: '{{ heapster_namespace }}'
    binary: '{{ bin_dir }}/helm'
    values: >-
      {{ [kube_heapster__default_values] + heapster_external_values }}
    state: latest
  register: heapster_helm_install
  run_once: true

- debug:
    var: heapster_helm_install
  run_once: true
  when: debug|bool
