- name: assert {{ inventory_hostname }} has vgs correctly declared
  assert:
    that:
      - 'item.value.drives|length > 0'
  with_dict: '{{ metal_k8s_lvm.vgs }}'

- name: start lvm storage setup
  debug:
    msg: "Start LVM storage setup"

- name: display metal_k8s_lvm config
  debug:
    msg: '{{ metal_k8s_lvm.vgs }}'
  when: debug|bool

- name: create the vgs
  lvg:
    pvs: '{{ item.value.drives|join(",") }}'
    vg: '{{ item.key }}'
    state: present
  with_dict: '{{ metal_k8s_lvm.vgs }}'
