- name: "LVM Setup: Assert {{ inventory_hostname }} has vgs correctly declared"
  assert:
    that:
      - 'item.value.drives|length > 0'
  with_dict: '{{ metal_k8s_lvm.vgs }}'

- name: "LVM Setup: Check LVM packages"
  package:
    name: lvm2
    state: present

- name: "LVM Setup: Display metal_k8s_lvm config"
  debug:
    msg: '{{ metal_k8s_lvm.vgs }}'
  when: debug|bool

- name: "LVM Setup: Create the LVM Volume Groups"
  lvg:
    pvs: '{{ item.value.drives|join(",") }}'
    vg: '{{ item.key }}'
    state: present
  with_dict: '{{ metal_k8s_lvm.vgs }}'
