---
- name: Set up package repositories
  hosts: metalk8s-repository
  tags:
  - repository
  roles:
    - role: repository
      tags: ['role::repository']
    - role: repository/populate
      tags: ['role::repository::populate']
