- hosts: kube-node
  any_errors_fatal: '{{ any_errors_fatal | default(true) }}'
  tags:
    - lvm-storage
  roles:
    - role: metalk8s_lvm_vg
    - role: setup_lvm_vg
      vars:
        vg_list: '{{ metalk8s_lvm_all_vgs }}'
    - role: setup_lvm_lv
